global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'iot-ml-system'
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker containers metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s

  # IoT Simulator metrics
  - job_name: 'iot-simulator'
    static_configs:
      - targets: ['iot-simulator:8080']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # ML Server metrics
  - job_name: 'ml-server'
    static_configs:
      - targets: ['ml-server:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Data Consumer metrics
  - job_name: 'data-consumer'
    static_configs:
      - targets: ['data-consumer:8080']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Streamlit Dashboard metrics
  - job_name: 'streamlit-dashboard'
    static_configs:
      - targets: ['streamlit-dashboard:8501']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
